name: Try Runtime

on:
  issue_comment:
    types: [created]

permissions:
  # Necessary to comment on the issue.
  issues: write

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_TERM_COLOR: always

  RUST_BACKTRACE: full

jobs:
  try-runtime:
    if: >
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/bot try-runtime')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add the runtime name and URI here.
        runtime:
          - name: polkadot-runtime
            uri: wss://rpc.polkadot.io
          - name: staging-kusama-runtime
            uri: wss://kusama-rpc.polkadot.io
    steps:
      - name: Fetch latest code
        uses: actions/checkout@v4
      - name: Try-Runtime
        # It is recommended to use a specific version of the action in production.
        #
        # For example:
        # uses: hack-ink/polkadot-runtime-releaser/action/try-runtime@vX.Y.Z
        uses: hack-ink/polkadot-runtime-releaser/action/try-runtime@main
        with:
          # The target runtime to build.
          #
          # For example, `polkadot-runtime` or `staging-kusama-runtime`.
          runtime: ${{ matrix.runtime.name }}
          # The features to enable for this try-runtime build.
          features: try-runtime
          # Rust toolchain version to build the runtime.
          toolchain-ver: 1.81.0
          # Try-Runtime CLI version.
          try-runtime-ver: 0.8.0
          # The URI of the node to connect to fetch the state.
          uri: ${{ matrix.runtime.uri }}
